### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [PicoGeyer/zsh-pico-prompt#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by picogeyer** [comment]
![zsh-pico-prompt](https://user-images.githubusercontent.com/1290303/208320543-54b96f6c-7073-4273-b925-d0ddc4dfc3d7.png)

**Comment by picogeyer** [comment]
@unixorn Thanks for the feedback, I've added the screenshot now.
I didn't expect the plugin to be used by anyone but me :)
